#!/bin/bash

# Script de ayuda para MIES Conservación
# Uso: ./help.sh

echo "📚 MIES Conservación - Guía de Scripts"
echo "======================================"
echo ""
echo "🚀 Scripts Disponibles:"
echo ""
echo "  📄 start-simple.sh    - Inicia el servidor con Bun (modo daemon)"
echo "  📄 stop-simple.sh     - Detiene el servidor daemon"
echo "  📄 status.sh          - Muestra el estado del servidor"
echo "  📄 start-pm2.sh       - Inicia con PM2 (recomendado para producción)"
echo "  📄 monitor.sh         - Monitor en tiempo real del sistema"
echo ""
echo "💡 Formas de ejecutar:"
echo ""
echo "  Desde la raíz del proyecto:"
echo "    ./scripts/start-simple.sh"
echo "    ./scripts/status.sh"
echo "    ./scripts/stop-simple.sh"
echo ""
echo "  Desde la carpeta scripts:"
echo "    cd scripts"
echo "    ./start-simple.sh"
echo "    ./status.sh"
echo "    ./stop-simple.sh"
echo ""
echo "  Usando npm scripts:"
echo "    npm run start-daemon     # ./scripts/start-simple.sh"
echo "    npm run stop-daemon      # ./scripts/stop-simple.sh"
echo "    npm run status-daemon    # ./scripts/status.sh"
echo ""
echo "🔧 Scripts de desarrollo:"
echo ""
echo "  bun run dev              - Servidor en modo desarrollo"
echo "  bun run build            - Compilar proyecto"
echo "  bun run build-frontend   - Compilar solo frontend"
echo ""
echo "📊 PM2 (Producción):"
echo ""
echo "  bun run pm2:start        - Iniciar con PM2"
echo "  bun run pm2:status       - Estado de PM2"
echo "  bun run pm2:logs         - Ver logs de PM2"
echo "  bun run pm2:stop         - Detener PM2"
echo ""
echo "🌐 URLs de la aplicación:"
echo ""
echo "  📱 Móvil:      http://localhost:3001/"
echo "  💻 Escritorio: http://localhost:3001/desktop"
echo "  🔗 API:        http://localhost:3001/api"
echo ""
echo "📁 Archivos importantes:"
echo ""
echo "  📄 .env                  - Variables de entorno"
echo "  📄 logs/out.log          - Logs del servidor"
echo "  📄 logs/error.log        - Logs de errores"
echo "  📄 ecosystem.config.cjs  - Configuración PM2"
echo ""
